# Generated by Django 5.0.2 on 2024-05-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
