# Generated by Django 5.0.2 on 2024-05-15 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0002_alter_prompt_created'),
        ('users', '0004_profilegithub'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prompt',
            old_name='message',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='prompt',
            old_name='name',
            new_name='tag',
        ),
        migrations.AlterField(
            model_name='prompt',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profilegithub'),
        ),
    ]
