# Generated by Django 5.0.2 on 2024-05-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileGithub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('image', models.URLField()),
            ],
        ),
    ]
